### ISSUE TITLE
goals

### ISSUE THREAD

**Issue by aheckmann** [mongodbinc-interns/mongoose#1]
- [x] [mquery integration](https://github.com/LearnBoost/mongoose/issues/1435)
- [x] [connection pool sharing support](https://github.com/LearnBoost/mongoose/issues/1124) (3.7)
- [x] [nested $or and $and support](https://github.com/LearnBoost/mongoose/issues/676)
- [ ] [DBref support](https://github.com/LearnBoost/mongoose/pull/525) - external module
- [x] [geoSearch](https://github.com/LearnBoost/mongoose/issues/1372) support
- [x] [geoNear](https://github.com/LearnBoost/mongoose/issues/1371) support
- [x] [geoWithin](https://github.com/LearnBoost/mongoose/issues/1455) support
- [x] [support overwriting documents during updates](https://github.com/LearnBoost/mongoose/issues/1081) (mquery ties in here)
- [ ] schema support of first class [arrays of arrays](https://github.com/LearnBoost/mongoose/issues/1361)
- [x] automated benchmarks
- [x] improved examples
